---
deployment:
  targets:
    - name: production
      domain: example.com
      path: /public_html/gaiusjimedits
      excluded_files:
        - .git
        - .gitignore
        - .env
        - .env.local
        - .env.*.local
        - npm-debug.log
        - yarn-error.log
        - .DS_Store
        - .idea
        - .vscode
        - coverage
        - package-lock.json
      scripts:
        pre_deploy:
          - npm install
        post_deploy:
          - npm run build
